### ISSUE TITLE
LoginView, MakeAccountView, BoardView 디자인 개선

### ISSUE THREAD

**Issue by MoonGoon72** [CNU-SW-Academy-iOS/OrderMate#37]
## Description
LoginView의 버튼 색상을 green 0로 바꾸고, cornerRadius 추가.
BoardView도 비슷하게 바꿔야 합니다. 근데 PreView에서는 안보이는 것 같아서 시뮬레이터 켜가면서 해봐야 하는걸까요?

**Comment by cyberman0306** [comment]
저는 매번 시뮬레이터만 쓰긴합니다
